services:
  landing-page:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    # Eliminamos el volumen para evitar interferencias con los archivos estáticos
    restart: unless-stopped
