version: '3'

services:
  landing-page:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4321:4321"
    volumes:
      - ./src:/app/src
    environment:
      - NODE_ENV=production
    restart: unless-stopped
